# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-IRR
version:      0.06
version_from: lib/Net/IRR.pm
installdirs:  site
requires:
    Carp:                          0
    Net::TCP:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
